import sqlite3
import datetime

conn = sqlite3.connect('newDB2.db')
c = conn.cursor()

c.execute(""" CREATE TABLE `Food` ( `id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` TEXT NOT NULL UNIQUE ) """)
c.execute(""" CREATE TABLE `Optional` ( `id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` TEXT NOT NULL UNIQUE ) """)
c.execute(""" CREATE TABLE `Orders` ( `id` INTEGER PRIMARY KEY AUTOINCREMENT, `time` NUMERIC NOT NULL ) """)
c.execute(""" CREATE TABLE "DetailOrder" ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `orderID` INTEGER NOT NULL, `foodID` INTEGER NOT NULL, FOREIGN KEY(`foodID`) REFERENCES `Food`(`id`), FOREIGN KEY(`orderID`) REFERENCES `Orders`(`id`)) """)
c.execute("""CREATE TABLE `Detailorder_option` (`id`	INTEGER PRIMARY KEY AUTOINCREMENT,`orderDetailID`	INTEGER,`optionalID`	INTEGER,FOREIGN KEY(`orderDetailID`) REFERENCES `DetailOrder`(`id`));""")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Espresso')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Cappuccino')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Latte')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Mocha')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Tea')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Green_Tea_with_Milk')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Milk_Tea')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Dark_chocolate')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Fresh_Milk')")
c.execute("INSERT INTO Food (name) VALUES ('Hot_Chocolate')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Espresso')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Cappuccino')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Latte')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Mocha')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Honey_Black_Coffee')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Honey_Black_Coffee_Lemon')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Green_Tea_with_Milk')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Milk_Tea')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Lemonade_Tea')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Black_Tea')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Matcha_Honey')") 
c.execute("INSERT INTO Food (name) VALUES ('Ice_Dark_chocolate')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Fresh_Milk')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Chocolate')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Lynchee_Juice')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Strawberry_juice')")
c.execute("INSERT INTO Food (name) VALUES ('Ice_Kiwi_Juice')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Espresso')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Cappuccino')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Latte')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Mocha')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Green_Tea_with_Milk')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Milk_Tea')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Dark_chocolate')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Fresh_Milk')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Chocolate')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Lynchee_Juice')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Strawberry_juice')")
c.execute("INSERT INTO Food (name) VALUES ('Frappe_Kiwi_Juice')")
c.execute("INSERT INTO Food (name) VALUES ('Cookie')")
c.execute("INSERT INTO Food (name) VALUES ('Brownies')")
c.execute("INSERT INTO Food (name) VALUES ('Cake')")
c.execute("INSERT INTO Food (name) VALUES ('Croissant')")
c.execute("INSERT INTO Food (name) VALUES ('hotdog')")
c.execute("INSERT INTO Food (name) VALUES ('Toast')")
c.execute("INSERT INTO Food (name) VALUES ('honey-toast')")
c.execute("INSERT INTO Food (name) VALUES ('hamburger')")

c.execute("INSERT INTO Optional (name) VALUES ('Normal')")
c.execute("INSERT INTO Optional (name) VALUES ('No_Sugar')")
c.execute("INSERT INTO Optional (name) VALUES ('Low_Sugar')")
c.execute("INSERT INTO Optional (name) VALUES ('Add_Sugar')")
c.execute("INSERT INTO Optional (name) VALUES ('No_Milk')")
c.execute("INSERT INTO Optional (name) VALUES ('Low_Milk')")
c.execute("INSERT INTO Optional (name) VALUES ('Add_Milk')")
c.execute("INSERT INTO Optional (name) VALUES ('ฺNo_Cream')")
c.execute("INSERT INTO Optional (name) VALUES ('Low_Cream')")
c.execute("INSERT INTO Optional (name) VALUES ('Add_Cream')")
c.execute("INSERT INTO Optional (name) VALUES ('Whip_Cream')")

conn.commit()